language: node_js
node_js:
- '0.10'
script: npm run-script doc && npm run-script test
deploy:
  provider: s3
  access_key_id: AKIAIA6HQQI46VJ55NBA
  skip_cleanup: true
  secret_access_key:
    secure: SmkhvvNFQzf+XomietqCPILsGz9ndcpsMwOa+63F8431IavLU76WUr770qNWLFsZqL1SQUVhdN+jMcQkhDf2ITmAqpGiabGFrBUKD607lKdw17EB0eAG17Aoo9VBUNu4rw/EztVnXChj5FtEhaIRXb/2jKofP0BeT1iv+YmzCP0=
  bucket: lightsofapollo-oss
  local-dir: ./doc
  upload-dir: taskcluster-client
  on:
    repo: taskcluster/client
    branch: initial
