language: node_js
node_js:
- '0.10'
script: npm run-script doc && npm run-script test
deploy:
  provider: s3
  access_key_id: AKIAJRL3G6MJIOJSMUFA
  secret_access_key:
    secure: QCNL0A+5C4KTpPHcobL8iIhPeduw0iZe8Qyk1xnRKs1FL1/SBBMTTPsX/5ktr4gioDICeHsRh9V86S1M/fgq589DOgYGcCJc3Clnv9aXmhClKMl0WwnDZax6l6WHQwOidB3qGJ3sR28IIuf/bO5fhzYSabPmfY6Q6MMkFLtFxNk=
  bucket: lightsofapollo-oss
  local-dir: doc/
  on:
    repo: taskcluster/client
    branch: initial
